### ISSUE TITLE
The payment fee is always displayed excluding tax regardles of the price display settings

### ISSUE THREAD

**Issue by peter-k77** [mageprince/magento2-paymentfee#8] opened 2020-10-29 22:13 UTC
Extension works well, but it does not respect tax display setting:
Stores --> Settings --> Configuration: Sales --> Tax --> 
   Price Display Settings / 
   Shopping Cart Display Settings / 
   Orders, Invoices, Credit Memos Display Settings 
       --> Display Shipping Amount: Including Tax / Excluding Tax

Price is always shown without tax regardless of the settings.
I would appreciate, if the extension can be modified to respect the above price display settings.
The tax calculation is correct, the problem is only with the display of the price.

Steps to reproduce:
	1. Create Payment Method Payment Fee - fixed amount $10
	2. Set Tax Settings --> Calculate Tax: Yes
	3. Set Tax Settings --> Tax Class: select a tax with 20% tax rate
	4. Stores --> Settings --> Configuration: Sales --> Tax --> Price Display Settings / Shopping Cart Display Settings set 'Display Shipping Prices' to 'Including Tax'
	5. Place an order
	6. Check Order Summary on the Checkout Page, Order confirmation email, etc.

Expected result:
Payment fee:  $12  [i.e. $10 + 20% tax]

Actual result:
Payment fee: $10

**Comment by maya5510** [comment] 2020-10-31 18:03
I have same problem with this module

**Comment by mageprince** [comment] 2020-11-01 14:24
Hi @peter-k77 Thanks for letting us know your concerns. This is currently on the development list. We will inform you here once available with the future version of the extension.
Duplicate of: https://github.com/mageprince/magento2-paymentfee/issues/5

**Comment by mageprince** [comment] 2020-12-05 15:24
Hi @peter-k77 Thank you for your patience. This is now implemented with the latest version of the module(2.1.0). You can now select text display type (Incl. Tax, Excl Tax, or Both) from the configuration.

**Closed as completed by mageprince** 2020-12-05 15:24 UTC
