### ISSUE TITLE
Tax Calculation issue Magento 2.3.4

### ISSUE THREAD

**Issue by maya5510** [mageprince/magento2-paymentfee#9] opened 2020-10-31 18:02 UTC
Hello

Tax Calculation is not working. If I mark yes or no, there is no difference, at all. The fee is calculated from the net price. I am using Magento 2.3.4 and your module version 2.0.3

Regards

**Comment by mageprince** [comment] 2020-11-01 14:24
Hi @maya5510  Thanks for letting us know your concerns. This is currently on the development list. We will inform you here once available with the future version of the extension.
Duplicate of: #5

**Comment by mageprince** [comment] 2020-12-05 15:24
Hi @maya5510, Thank you for your patience. This is now implemented with the latest version of the module(2.1.0). You can now select text display type (Incl. Tax, Excl Tax, or Both) from the configuration.

**Closed as completed by mageprince** 2020-12-05 15:24 UTC
